"""Initial migration

Revision ID: 45586574d74d
Revises: 
Create Date: 2025-09-02 00:46:30.834947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45586574d74d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sender_email', sa.String(length=120), nullable=True),
    sa.Column('receiver_email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entry_timestamp'), ['timestamp'], unique=False)

    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_plain', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sender_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('sending_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('telegram_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.String(length=255), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_login_success', sa.Boolean(), nullable=True),
    sa.Column('alert_login_failure', sa.Boolean(), nullable=True),
    sa.Column('alert_sending_started', sa.Boolean(), nullable=True),
    sa.Column('alert_sending_paused_resumed_stopped', sa.Boolean(), nullable=True),
    sa.Column('alert_batch_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_errors', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_emails', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('emails_failed', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['message_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiver_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receiver_email')
    op.drop_table('campaign')
    op.drop_table('user')
    op.drop_table('telegram_settings')
    op.drop_table('sender_email')
    op.drop_table('message_template')
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entry_timestamp'))

    op.drop_table('log_entry')
    # ### end Alembic commands ###
