"""Allow nullable template_id in Campaign

Revision ID: b6961f8e3332
Revises: 45586574d74d
Create Date: 2025-09-02 00:57:58.107316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6961f8e3332'
down_revision = '45586574d74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('template_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
